apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demowidgets.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: string
                status:
                  type: string
  scope: Namespaced
  names:
    plural: demowidgets
    singular: demowidget
    kind: DemoWidget
    shortNames:
    - dw