apiVersion: v1
kind: ConfigMap
metadata:
  name: flex-configmap
data:
  k8s-crd.yaml: | 
    ---
    integrations:
      - name: nri-flex
        # interval: 30s
        config:
          name: K8sCRDSample
          # global:
          #   base_url: https://kubernetes.default.svc.cluster.local
          apis:
            # - name: stuff
            #   commands:
            #     - run: cat /var/run/secrets/kubernetes.io/serviceaccount/token | awk '{printf "{\"value\":\"%s\"}",$1}'
            #   jq: '.'
            #   store_variables:
            #     value: token
            #   ignore_output: true
            - name: demoWidgetCRD
              event_type: K8sCRDSample
              commands: 
                - run: 'curl -s https://kubernetes.default.svc.cluster.local/apis/example.com/v1/demowidgets --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
              jq: '.items[] | { name: .metadata.name, status: .spec.status, enabled: .spec.enabled, kind: .kind, apiVersion: .apiVersion}'